apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-virtual-service
spec:
  hosts:
  - hello.example.com
  gateways:
  - app-gateway-istio-gateway
  http:
  - name: "Hello World route mapping"
    match:
    - uri:
        prefix: /
      ignoreUriCase: true
    rewrite:
      uri: "/"
    route:
    - destination:
        host: hello-world.default.svc.cluster.local
